name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
      - '.editorconfig'
      - '.spi.yml'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: macOS-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.3.app/Contents/Developer
    strategy:
      matrix:
        destination:
          - "platform=macOS"
          - "platform=iOS Simulator,name=iPhone 12"
          - "platform=visionOS Simulator,name=Apple Vision Pro"
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: set -o pipefail && xcodebuild -scheme ChimeKit-Package -destination "${{ matrix.destination }}" test | xcbeautify
