name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
      - '.editorconfig'
      - '.spi.yml'
  pull_request:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer

jobs:
  test:
    name: Test
    runs-on: macOS-14

    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: set -o pipefail && xcodebuild -scheme ChimeKit-Package -destination "platform=macOS" test | xcbeautify
