name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

env:
  DEVELOPER_DIR: /Applications/Xcode_14.1.app/Contents/Developer

jobs:
  test:
    name: Test
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v2
      - name: Test ChimeExtensionInterface
        run: set -o pipefail && xcodebuild -scheme ChimeExtensionInterface -destination "platform=macOS" test | xcpretty
      - name: Test ChimeLSPAdapter
        run: set -o pipefail && xcodebuild -scheme ChimeLSPAdapter -destination "platform=macOS" test | xcpretty
