import Foundation
import UniformTypeIdentifiers

public extension UTType {
	static let coffeeScriptSource = UTType(importedAs: "org.coffeescript.coffeescript")
	static let cSharpSource = UTType(importedAs: "com.microsoft.c-sharp")
	static let cssSource = UTType(importedAs: "public.css")
	static let dSource = UTType(importedAs: "org.dlang.d")
	static let dartSource = UTType(importedAs: "dev.dart.dart-script")
	static let dockerfile = UTType(importedAs: "com.docker.dockerfile")
	static let clojureSource = UTType(importedAs: "org.clojure.source")
	static let cmakeSource = UTType(importedAs: "org.cmake.cmake")
	static let elixirSource = UTType(importedAs: "org.elixir-lang.source")
	static let elmSource = UTType(importedAs: "org.elm-lang.source")
	static let erlangSource = UTType(importedAs: "org.erlang.erlang")
	static let fortranSource = UTType(importedAs: "public.fortran-source")
	static let gitattributesFile = UTType(importedAs: "com.git-scm.attributes")
	static let gitignoreFile = UTType(importedAs: "com.git-scm.ignore")
    static let goSource = UTType(importedAs: "dev.go.go-source")
    static let goModFile = UTType(importedAs: "dev.go.go-module")
    static let goSumFile = UTType(importedAs: "dev.go.go-sum")
	static let goWorkFile = UTType(importedAs: "dev.go.go-work")
	static let hackSource = UTType(importedAs: "org.hacklang.source")
	static let haskellSource = UTType(importedAs: "org.haskell.source")
	static let hclSource = UTType(importedAs: "com.hashicorp.hcl")
	static let javaSource = UTType(importedAs: "com.sun.java-source")
	static let juliaSource = UTType(importedAs: "org.julialang.source")
	static let kotlinSource = UTType(importedAs: "org.kotlinlang.source")
	static let latexSource = UTType(importedAs: "org.latex-project.latex")
    static let luaSource = UTType(importedAs: "org.lua.source")
	static let markdown = UTType(importedAs: "net.daringfireball.markdown")
	static let ocamlInterface = UTType(importedAs: "org.ocaml.ocaml-interface")
	static let ocamlSource = UTType(importedAs: "org.ocaml.ocaml")
	static let pascalSource = UTType(importedAs: "public.pascal-source")
	static let patchFile = UTType(importedAs: "public.patch-file")
	static let rSource = UTType(importedAs: "org.r-project.r")
	static let racketSource = UTType(importedAs: "org.racket-lang.source")
	static let rustSource = UTType(importedAs: "org.rust-lang.rust-script")
	static let scalaSource = UTType(importedAs: "org.scala-lang.scala-source")
	static let sqlSource = UTType(importedAs: "org.iso.sql")
	static let sshConfigurationFile = UTType(importedAs: "com.ssh.client-config")
	static let tclSource = UTType(importedAs: "tk.tcl.tcl")
	static let terraformSource = UTType(importedAs: "com.hashicorp.terraform-source")
	static let treeSitterQuerySource = UTType(importedAs: "io.github.tree-sitter.query-source")
	static let toml = UTType(importedAs: "public.toml")
	static let typescriptSource = UTType(importedAs: "org.typescriptlang.source")
	static let typescriptJSXSource = UTType(importedAs: "org.typescriptlang.jsx-source")
	static let zigSource = UTType(importedAs: "org.ziglang.zig")
}
